version: '2'

services:
  ca.sardex.sardex.net:
    image: hyperledger/fabric-ca:1.2.0
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.sardex.sardex.net
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.sardex.sardex.net-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/f0033ae539e86794755eee0aadc61213b9c670144718cbbd28b656383de7fc50_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/sardex.sardex.net/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.sardex.sardex.net

  orderer.sardex.net:
    container_name: orderer.sardex.net
    image: hyperledger/fabric-orderer:1.2.0
    environment:
      - ORDERER_GENERAL_LOGLEVEL=debug
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/etc/hyperledger/configtx/interlace-genesis.block
      - ORDERER_GENERAL_LOCALMSPID=InterlaceOrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/msp/orderer/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    ports:
      - 7050:7050
    volumes:
        - ./:/etc/hyperledger/configtx
        - ./crypto-config/ordererOrganizations/sardex.net/orderers/orderer.sardex.net/msp:/etc/hyperledger/msp/orderer/msp

  peer0.sardex.sardex.net:
    container_name: peer0.sardex.sardex.net
    image: hyperledger/fabric-peer:1.2.0
    environment:
      - CORE_LOGGING_LEVEL=debug
      - CORE_CHAINCODE_LOGGING_LEVEL=DEBUG
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer0.sardex.sardex.net
      - CORE_PEER_ADDRESS=peer0.sardex.sardex.net:7051
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=composer_default
      - CORE_PEER_LOCALMSPID=SardexMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/peer/msp
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb:5984
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    ports:
      - 7051:7051
      - 7053:7053
    volumes:
        - /var/run/:/host/var/run/
        - ./:/etc/hyperledger/configtx
        - ./crypto-config/peerOrganizations/sardex.sardex.net/peers/peer0.sardex.sardex.net/msp:/etc/hyperledger/peer/msp
        - ./crypto-config/peerOrganizations/sardex.sardex.net/users:/etc/hyperledger/msp/users
    depends_on:
      - orderer.sardex.net
      - couchdb

  couchdb:
    container_name: couchdb
    image: hyperledger/fabric-couchdb:0.4.10
    ports:
      - 5984:5984
    environment:
      DB_URL: http://localhost:5984/member_db
