NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca.sardex.sardex.net-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca.sardex.sardex.net-cert.pem
    OrganizationalUnitIdentifier: peer
